export const STORE_CONFIG = {
  name: 'WEAR & GO',
  tagline: 'Style That Moves With You.',
  currency: '₹',
  freeShippingThreshold: 999,
  shippingFee: 99,
  returnPeriodDays: 7,
  supportEmail: 'wear.and.go.official@gmail.com',
  supportPhone: '+91 74002 45941',
  whatsappNumber: '+917400245941',
  address: 'Shop No. 3, Yamuna Bai Chawl, Asalpha Village, Ghatkopar West, Mumbai - 400084',
  social: {
    instagram: 'https://instagram.com/wearandgo',
    facebook: 'https://facebook.com/wearandgo',
    youtube: 'https://youtube.com/wearandgo',
  },
};

export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Delhi NCR',
  'Chandigarh',
  'Jammu and Kashmir',
  'Ladakh',
  'Puducherry',
];

export const SITE_CONFIG = STORE_CONFIG;
